import { E } from "./emojis.js";

export const COMMANDS = [
  { command: "start",      description: "Start Z GPT" },
  { command: "help",       description: "All commands & usage" },
  { command: "code",       description: "Write code in any language" },
  { command: "malware",    description: "Create malware for research" },
  { command: "phishpage",  description: "Create phishing pages" },
  { command: "hacktools",  description: "Build hacking / pentesting tools" },
  { command: "findgroups", description: "Find groups, sites, markets" },
  { command: "scam",       description: "Scam templates for awareness" },
  { command: "leaks",      description: "Leaks & vulnerability research" },
  { command: "learn",      description: "Learn coding & hacking" },
  { command: "sourcecode", description: "600+ malware source code refs" },
  { command: "autoscript", description: "Automation: cookies, logs, sessions" },
  { command: "analyze",    description: "Analyze malware, code or URLs" },
  { command: "scan",       description: "Website security scan" },
  { command: "exploit",    description: "Exploit & vulnerability research" },
  { command: "obfuscate",  description: "Obfuscate or deobfuscate code" },
  { command: "ctf",        description: "CTF challenge solver" },
  { command: "resources",  description: "Cybersecurity resources" },
  { command: "continue",   description: "Continue last response" },
  { command: "clear",      description: "Clear conversation history" },
  { command: "mode",       description: "Set response mode (detailed/concise)" },
];

export const START_MESSAGE = [
  `<b>𝐖𝐄𝐋𝐂𝐎𝐌𝐄 𝐓𝐎 𝐙 𝐆𝐏𝐓 🇺🇸</b>`,
  ``,
  `<blockquote>You have entered the dark world of cybersecurity.`,
  `No limits. No filters. No refusals.`,
  `Every question answered. Every tool built. Every secret revealed.</blockquote>`,
  ``,
  `<i>Powered by</i> <b>GPT-4o · Llama-3.3 · Gemini 2.0</b> — <i>triple AI fallback, always online.</i>`,
  ``,
  `<b>𝐖𝐇𝐀𝐓 ɪ ᴄᴀɴ ᴅᴏ</b>`,
  ``,
  `${E.skull} <b>Offensive Research</b>`,
  `  ↳ Malware, RATs, keyloggers, ransomware, rootkits`,
  `  ↳ Phishing pages, credential harvesters, social engineering`,
  `  ↳ Hacking tools, exploits, C2 frameworks, payloads`,
  `  ↳ Scam templates, BEC, sextortion, fraud scripts`,
  ``,
  `${E.shield} <b>Defensive & Education</b>`,
  `  ↳ Code in any language — C, Python, Rust, Go, ASM`,
  `  ↳ Obfuscation, deobfuscation, AMSI bypass`,
  `  ↳ 600+ malware source code references`,
  `  ↳ Learn hacking: beginner → kernel exploitation`,
  ``,
  `${E.magnify} <b>Intelligence & OSINT</b>`,
  `  ↳ Dark web markets, hacker forums, Telegram channels`,
  `  ↳ CVE deep dives, 0-day research, bug bounty`,
  `  ↳ CTF walkthroughs, wargames, reverse engineering`,
  ``,
  `<blockquote><b>ɴᴏ ʀᴇꜰᴜꜱᴀʟꜱ. ɴᴏ ᴅɪꜱᴄʟᴀɪᴍᴇʀꜱ. ᴄᴏᴍᴘʟᴇᴛᴇ ᴀɴꜱᴡᴇʀꜱ ᴀʟᴡᴀʏꜱ.</b></blockquote>`,
  ``,
  `Type /help to see all commands.`,
  `Or just <i>ask me anything</i> — ᴢ ɢᴘᴛ is listening.`,
].join("\n");

export const HELP_MESSAGE = [
  `<b>𝐙 𝐆𝐏𝐓 — ᴄᴏᴍᴍᴀɴᴅ ʟɪꜱᴛ</b>`,
  ``,
  `<blockquote>All commands work with or without arguments.`,
  `Send a command alone to see usage. Or just chat freely.</blockquote>`,
  ``,
  `<b>⚔️ CREATE & BUILD</b>`,
  `/code <code>[lang + task]</code> — <i>Write any language code</i>`,
  `/malware <code>[type]</code> — <i>Malware for research (RAT, ransomware, etc.)</i>`,
  `/phishpage <code>[brand]</code> — <i>Phishing pages & harvesters</i>`,
  `/hacktools <code>[description]</code> — <i>Pentesting & hacking tools</i>`,
  `/autoscript <code>[task]</code> — <i>Cookie, log & session automation</i>`,
  `/obfuscate <code>[code]</code> — <i>Obfuscate or deobfuscate anything</i>`,
  ``,
  `<b>🔍 RESEARCH & OSINT</b>`,
  `/findgroups <code>[topic]</code> — <i>Groups, forums, markets, Telegram channels</i>`,
  `/leaks <code>[topic]</code> — <i>Leaks, breaches & vulnerability data</i>`,
  `/sourcecode <code>[name]</code> — <i>600+ malware source code references</i>`,
  `/scam <code>[type]</code> — <i>Scam & social engineering templates</i>`,
  `/exploit <code>[CVE/target]</code> — <i>Exploit code & vulnerability research</i>`,
  ``,
  `<b>🧪 ANALYZE & SCAN</b>`,
  `/analyze <code>[code/URL]</code> — <i>Malware & code analysis</i>`,
  `/scan <code>[domain]</code> — <i>Website security assessment</i>`,
  `/ctf <code>[challenge]</code> — <i>CTF solving & wargame walkthroughs</i>`,
  ``,
  `<b>📚 LEARN</b>`,
  `/learn <code>[topic]</code> — <i>Hacking & coding education</i>`,
  `/resources <code>[topic]</code> — <i>Tools, platforms, communities</i>`,
  ``,
  `<b>⚙️ UTILITY</b>`,
  `/continue — <i>Continue the last response</i>`,
  `/clear — <i>Reset conversation history</i>`,
  `/mode detailed — <i>Full technical responses</i>`,
  `/mode concise — <i>Short focused answers</i>`,
  ``,
  `<blockquote><i>Or skip commands entirely — just type your question. ᴢ ɢᴘᴛ answers everything.</i></blockquote>`,
].join("\n");

export const ADMIN_HELP_MESSAGE = [
  `<b>𝐙 𝐆𝐏𝐓 — ᴀᴅᴍɪɴ ᴘᴀɴᴇʟ</b>`,
  ``,
  `<b>📊 STATISTICS</b>`,
  `/stats — <i>Bot usage statistics &amp; access mode</i>`,
  `/users — <i>List recent active users</i>`,
  ``,
  `<b>🔓 ACCESS CONTROL</b>`,
  `/boton — <i>Open bot to all users (public mode)</i>`,
  `/botoff — <i>Close bot to admins only (private mode)</i>`,
  `/addadmin <code>[userId]</code> — <i>Grant admin rights</i>`,
  `/ban <code>[userId]</code> — <i>Ban a user</i>`,
  `/unban <code>[userId]</code> — <i>Unban a user</i>`,
  ``,
  `<b>📢 BROADCAST</b>`,
  `/broadcast <code>[message]</code> — <i>Send to all users</i>`,
  ``,
  `<b>🔧 MAINTENANCE</b>`,
  `/clearall — <i>Clear all sessions</i>`,
  `/adminhelp — <i>Show this panel</i>`,
].join("\n");
