/**
 * Standard Unicode emojis for use in Telegram Bot API HTML messages.
 * Note: <tg-emoji> custom emoji tags are NOT supported by the Bot API —
 * they are client-side only. Use plain Unicode emojis instead.
 */
export const E = {
  lightning:   "⚡",
  diamond:     "💎",
  star:        "⭐",
  shield:      "🛡",
  fire:        "🔥",
  rocket:      "🚀",
  skull:       "💀",
  lock:        "🔒",
  brain:       "🧠",
  sword:       "⚔",
  bug:         "👾",
  eye:         "👁",
  robot:       "🤖",
  crown:       "👑",
  globe:       "🌐",
  trophy:      "🏆",
  redcircle:   "🔴",
  greencircle: "🟢",
  bluecircle:  "🔵",
  wrench:      "🔧",
  gun:         "🔫",
  gem:         "💠",
  check:       "✅",
  cross:       "❌",
  warning:     "⚠️",
  key:         "🔑",
  magnify:     "🔍",
  target:      "🎯",
  sparkles:    "✨",
  bomb:        "💣",
  infinity:    "♾",
  chip:        "🖥",
  satellite:   "📡",
  alert:       "🚨",
  terminal:    "💻",
  dna:         "🧬",
  radioactive: "☢️",
  biohazard:   "☣️",
  forbidden:   "🚫",
  admin:       "👤",
  stats:       "📊",
  broadcast:   "📢",
  ban:         "⛔",
  unban:       "✔️",
  trash:       "🗑",
  clock:       "🕐",
  chart:       "📈",
};
